#! /bin/sh

sxhkd &

bspc config border_width         0
bspc config window_gap          16

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true
bspc config focus_by_distance    true
bspc config history_aware_focus  true

bspc monitor HDMI1 -d 6 7 8 9 10
bspc monitor eDP1 -d 1 2 3 4 5

bspc rule -a Gimp desktop=^8 state=floating follow=on
bspc rule -a Chromium desktop=^2
bspc rule -a mplayer2 state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off

feh --bg-scale $HOME/Pictures/ElCapitan.jpg
panel &
