#! /bin/sh

. panel_colors

clock() {
	date "+%a %b %d, %I:%M %p"
}

network() {
	ping -c 1 8.8.8.8 >/dev/null 2>&1 &&
		echo "online" || echo "offline"
}

volume() {
	volume=`pamixer --get-volume`
	mute=`pamixer --get-mute`
	if [ $mute = true ]; then
		echo "MUTE"
	else
		echo $volume
	fi
}

groups() {
	cur=`xprop -root _NET_CURRENT_DESKTOP | awk '{print $3}'`
	tot=`xprop -root _NET_NUMBER_OF_DESKTOPS | awk '{print $3}'`

	for w in `seq 0 $((cur - 1))`
		do line=" ${line}#"; done
	line=" ${line}%{F$COLOR_BLUE}#%{F- B-}"
	for w in `seq $((cur + 2)) $tot`
		do line=" ${line}#"; done
	echo $line
}

battery() {
	echo `acpi --battery | cut -d, -f2`
}

while :; do
	p="  "
	l="$(groups)"
	c="$(clock)"
	r="vol: $(volume)% | net: $(network) | bat: $(battery)"
	echo "%{l}$p$l%{c}$c%{r}$r$p"
	sleep 1
done
